name: dextr
channels:
  - damianavila82
  - satra
  - menpo
  - pluraldatum
  - glemaitre
  - soumith
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - pandas
  - notebook>=5.2.2
  - ipywidgets>=6.0.1
  - ipython>=6.2.1
  - pydot
  - h5py
  - scikit-image<=0.20
  - scikit-learn<=0.20
  - pytorch<=0.3.0
  - torchvision
  - opencv3>=3.0
  - tensorflow==1.4.0
  - appmode
  - pip:
    - keras==2.1.3
    - plotly==2.1.0
    - graphviz
    - tqdm
