name: mcdepi
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.6=1
  - fretbursts=0.7=py36h7eb728f_1
  - future=0.16.0=py36_0
  - hdf5=1.10.1=1
  - llvmlite=0.21.0=py36_0
  - lmfit=0.9.7=py36_0
  - lzo=2.10=0
  - numexpr=2.6.4=py36_0
  - phconvert=0.8.2=py36_0
  - pybroom=0.2=py36_0
  - pytables=3.4.2=py36_7
  - atomicwrites=1.1.5=py36_0
  - attrs=18.1.0=py36_0
  - backcall=0.1.0=py36_0
  - bleach=2.1.1=py36hd521086_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py36_0
  - cycler=0.10.0=py36h93f1223_0
  - cython=0.28.2=py36h14c3975_0
  - dbus=1.10.22=h3b5a359_0
  - decorator=4.1.2=py36hd076ac8_0
  - entrypoints=0.2.3=py36h1aec115_2
  - expat=2.2.5=he0dffb1_0
  - fontconfig=2.12.4=h88586e7_1
  - freetype=2.8=hab7d2ae_1
  - glib=2.53.6=h5d9569c_2
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.12.2=he3457e5_0
  - gstreamer=1.12.2=h4f93127_0
  - html5lib=1.0.1=py36h2f9c1c0_0
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2018.0.0=hc7b2577_8
  - ipykernel=4.8.2=py36_0
  - ipython=6.4.0=py36_1
  - ipython_genutils=0.2.0=py36hb52b0d5_0
  - ipywidgets=7.1.1=py36_0
  - jedi=0.11.0=py36_2
  - jinja2=2.10=py36ha16c418_0
  - joblib=0.11=py36_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py36h006f8b5_0
  - jupyter_client=5.1.0=py36h614e9ea_0
  - jupyter_core=4.4.0=py36h7c827e3_0
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=7.2.0=h7cc24e2_2
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.2.0=h9f7466a_2
  - libpng=1.6.32=hbd3595f_4
  - libsodium=1.0.15=hf101ebd_0
  - libstdcxx-ng=7.2.0=h7a57d05_2
  - libxcb=1.12=hcd93eb1_4
  - libxml2=2.9.4=h2e8b1d7_6
  - markupsafe=1.0=py36hd9260cd_1
  - matplotlib=2.1.1=py36ha26af80_0
  - mistune=0.8.1=py36h3d5977c_0
  - mkl=2018.0.2=1
  - mkl_fft=1.0.1=py36h3010b51_0
  - mkl_random=1.0.1=py36h629b387_0
  - more-itertools=4.2.0=py36_0
  - nbconvert=5.3.1=py36hb41ffb7_0
  - nbformat=4.4.0=py36h31c9010_0
  - ncurses=6.0=h9df7e31_2
  - notebook=5.2.2=py36h40a37e6_0
  - numba=0.36.2=np114py36hc6662d5_0
  - numpy=1.14.2=py36hdbf6ddf_1
  - openssl=1.0.2o=h20670df_0
  - pandas=0.22.0=py36hf484d3e_0
  - pandoc=1.19.2.1=hea2e7c5_1
  - pandocfilters=1.4.2=py36ha6701b7_1
  - parso=0.1.1=py36h35f843b_0
  - patsy=0.4.1=py36ha3be15e_0
  - pcre=8.41=hc27e229_1
  - pexpect=4.3.0=py36h673ed17_0
  - pickleshare=0.7.4=py36h63277f8_0
  - pip=10.0.1=py36_0
  - pluggy=0.6.0=py36hb689045_0
  - prompt_toolkit=1.0.15=py36h17d85b1_0
  - ptyprocess=0.5.2=py36h69acd42_0
  - py=1.5.3=py36_0
  - pygments=2.2.0=py36h0d3125c_0
  - pyparsing=2.2.0=py36hee85983_1
  - pyqt=5.6.0=py36h0386399_5
  - pytest=3.6.0=py36_1
  - python=3.6.4=hc3d631a_0
  - python-dateutil=2.6.1=py36h88d3b88_1
  - pytz=2017.3=py36h63b9c63_0
  - pyzmq=16.0.3=py36he2533c7_0
  - qt=5.6.2=h974d657_12
  - readline=7.0=ha6073c6_4
  - scikit-learn=0.19.1=py36h7aa7ec6_0
  - scipy=1.0.0=py36hbf646e7_0
  - seaborn=0.8.1=py36hfad7ec4_0
  - setuptools=36.5.0=py36he42e2e1_0
  - simplegeneric=0.8.1=py36h2cb9092_0
  - sip=4.18.1=py36h51ed4ed_2
  - six=1.11.0=py36h372c433_1
  - sqlite=3.20.1=hb898158_2
  - statsmodels=0.8.0=py36h8533d0b_0
  - terminado=0.6=py36ha25a19f_0
  - testpath=0.3.1=py36h8cadb63_0
  - tk=8.6.7=hc745277_3
  - tornado=4.5.2=py36h1283b2a_0
  - traitlets=4.3.2=py36h674d592_0
  - wcwidth=0.1.7=py36hdf4376a_0
  - webencodings=0.5.1=py36h800622e_1
  - wheel=0.30.0=py36hfd4bba0_1
  - widgetsnbextension=3.1.0=py36_0
  - xz=5.2.3=h55aa19d_2
  - yaml=0.1.7=had09818_2
  - zeromq=4.2.2=hbedb6e5_2
  - zlib=1.2.11=ha838bed_2
  - pip:
    - pycorrelate==0.3
    - randomgen==1.14.4
    - tables==3.4.2
prefix: /home/anto/.conda/envs/mcdepi

