name: spooky
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope
  - asn1crypto=0.24.0=py36_1003
  - attrs=18.2.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.0.2=py_0
  - blinker=1.4=py_1
  - boto3=1.9.57=py_0
  - botocore=1.12.57=py_0
  - bz2file=0.98=py_0
  - ca-certificates=2018.11.29=ha4d7672_0
  - certifi=2018.11.29=py36_1000
  - cffi=1.11.5=py36h5e8e0c9_1
  - chardet=3.0.4=py36_1003
  - cryptography=2.3.1=py36hdffb7b8_0
  - cryptography-vectors=2.3.1=py36_1000
  - cycler=0.10.0=py_1
  - cytoolz=0.9.0.1=py36h470a237_1
  - decorator=4.3.0=py_0
  - dill=0.2.8.2=py36_1000
  - docutils=0.14=py36_1001
  - entrypoints=0.2.3=py36_1002
  - freetype=2.9.1=h6debe1e_4
  - idna=2.7=py36_1002
  - ipykernel=5.1.0=py36h24bf2e0_1001
  - ipython=7.2.0=py36h24bf2e0_1000
  - ipython_genutils=0.2.0=py_1
  - jedi=0.13.1=py36_1000
  - jinja2=2.10=py_1
  - jmespath=0.9.3=py_1
  - joblib=0.13.0=py_0
  - jsonschema=3.0.0a3=py36_1000
  - jupyter_client=5.2.3=py_1
  - jupyter_core=4.4.0=py_0
  - jupyterlab=0.35.4=py36_0
  - jupyterlab_server=0.2.0=py_0
  - kiwisolver=1.0.1=py36h2d50403_2
  - libcxx=7.0.0=h2d50403_2
  - libffi=3.2.1=hfc679d8_5
  - libpng=1.6.36=ha92aebf_0
  - libsodium=1.0.16=h470a237_1
  - llvm-meta=7.0.0=0
  - markupsafe=1.1.0=py36h470a237_0
  - matplotlib=2.2.3
  - mistune=0.8.4=py36h470a237_0
  - mkl_fft=1.0.10=py36_0
  - mkl_random=1.0.2=py36_0
  - msgpack-numpy=0.4.3.2=py_0
  - msgpack-python=0.6.0=py36h2d50403_0
  - murmurhash=1.0.0=py36hfc679d8_0
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hfc679d8_1
  - nltk=3.2.5=py_0
  - nodejs=10.8.0=hfc679d8_1
  - notebook=5.7.2=py36_1000
  - oauthlib=2.1.0=py_0
  - openblas=0.2.20=8
  - openssl=1.0.2p=h470a237_1
  - pandas=0.23.4=py36hf8a1672_0
  - pandoc=2.5=0
  - pandocfilters=1.4.2=py_1
  - parso=0.3.1=py_0
  - pexpect=4.6.0=py36_1000
  - pickleshare=0.7.5=py36_1000
  - pip=18.1=py36_1000
  - plac=0.9.6=py_1
  - prometheus_client=0.4.2=py_0
  - prompt_toolkit=2.0.7=py_0
  - ptyprocess=0.6.0=py36_1000
  - pycparser=2.19=py_0
  - pygments=2.3.0=py_0
  - pyjwt=1.6.4=py_0
  - pyopenssl=18.0.0=py36_1000
  - pyparsing=2.3.0=py_0
  - pyrsistent=0.14.7=py36h470a237_0
  - pysocks=1.6.8=py36_1002
  - python=3.6.7=h5001a0f_1
  - python-crfsuite=0.9.6=py36h2d50403_0
  - python-dateutil=2.7.5=py_0
  - pytz=2018.7=py_0
  - pyzmq=17.1.2=py36hae99301_1
  - readline=7.0=haf1bffa_1
  - regex=2018.01.10=py36h470a237_0
  - requests=2.20.1=py36_1000
  - requests-oauthlib=1.0.0=py_1
  - s3transfer=0.1.13=py36_1001
  - scikit-plot=0.3.7=py_0
  - send2trash=1.5.0=py_0
  - setuptools=40.6.2=py36_0
  - six=1.11.0=py36_1001
  - smart_open=1.7.1=py_0
  - spacy=2.0.18=py36hfc679d8_0
  - sqlite=3.26.0=hb1c47c0_0
  - terminado=0.8.1=py36_1001
  - testpath=0.4.2=py36_1000
  - thinc=6.12.1=py36hf8a1672_0
  - tk=8.6.9=ha92aebf_0
  - toolz=0.9.0=py_1
  - tornado=5.1.1=py36h470a237_0
  - tqdm=4.28.1=py_0
  - traitlets=4.3.2=py36_1000
  - twython=3.7.0=py_0
  - ujson=1.35=py36h470a237_1
  - urllib3=1.23=py36_1001
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.32.3=py36_0
  - wrapt=1.10.11=py36h470a237_1
  - xz=5.2.4=h470a237_1
  - zeromq=4.2.5=hfc679d8_6
  - zlib=1.2.11=h470a237_3
  - blas=1.0=mkl
  - boto=2.49.0=py36_0
  - cymem=2.0.2=py36h04f5b5a_0
  - gensim
  - intel-openmp=2019.1=144
  - libgfortran
  - libopenblas=0.3.3=hdc02c5d_3
  - mkl=2018.0.3=1
  - numpy=1.15
  - numpy-base=1.15.4
  - preshed=2.0.1
  - scikit-learn=0.20.1
  - scipy=1.1.0
  - pip:
    - msgpack==0.6.0
prefix: /Users/veronica/miniconda3/envs/spooky

